name: Build

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: chetan/git-restore-mtime-action@v2
    - name: Cache  💾
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache
          pandoc-3.2-1-amd64.deb
        key: ${{ runner.os }}-pip-
        restore-keys: ${{ runner.os }}-pip-
    - name: Setup Python 🐍
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Setup pandoc ⚙️
      run: |
        sudo apt-get update
        test -f pandoc-3.2-1-amd64.deb || wget https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-1-amd64.deb
        sudo dpkg -i pandoc-3.2-1-amd64.deb
        pip install --upgrade pip
        pip install Pygments pandoc-include
    - name: Build 🏗️
      run: | 
        make all
        tree content/
        git checkout quartz
        cd quartz/
        npm i
        npx quartz create
        npx quartz build --serve --concurrency 8
