name: Build

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18.14
    - uses: chetan/git-restore-mtime-action@v2
    - name: Setup Python 🐍
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Setup pandoc ⚙️
      run: |
        sudo apt-get update
        test -f pandoc-3.2-1-amd64.deb || wget https://github.com/jgm/pandoc/releases/download/3.2/pandoc-3.2-1-amd64.deb
        sudo dpkg -i pandoc-3.2-1-amd64.deb
        pip install --upgrade pip
        pip install Pygments pandoc-include
    - name: Build 🏗️
      run: | 
        make all
        tree content/
    - name: Switching to quartz
        git checkout quartz
    - name: Install Dependencies
      run: npm ci
    - name: Build Quartz
      run: npx quartz build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
            path: public
    
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
